on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read   
    steps:
      - name: Save OIDC Token to file
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value > oidc_token.txt
      - name: Upload OIDC Token File
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: oidc_token.txt
