on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read   
    steps:
      - name: Save OIDC Token to file
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value > oidc_token.txt
      - name: Upload OIDC Token File
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: oidc_token.txt
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/780618082768/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-sa@fphouse-452913.iam.gserviceaccount.com"
      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
      - name: Upload file to Google Cloud Storage
        run: |
          echo "Hello World!" > test.txt  # Tạo file mẫu
          gcloud storage cp test.txt gs://fphouse/